swagger: '2.0'
info:
  version: 1.0.0
  title: DMC Resource Definition
  description: |
    **REST service interface definitions for Resources**
host: dmc.com
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /resources/about:
    get:
      tags:
        - about
        - not implemented
        - no tests
      description: Get information on UI Labs.
      responses:
        '200':
          description: Sends all general information about UI Labs
          schema:
            $ref: '#/definitions/UILabs'
  '/resources/about/{labId}':
    get:
      tags:
        - about
        - not implemented
        - no tests
      description: Get a specified lab's information
      parameters:
        - in: path
          name: labId
          description: Lab Id
          type: integer
          required: true
      responses:
        '200':
          description: Return specified lab
          schema:
            type: array
            items:
              $ref: '#/definitions/Lab'
  '/resources/shop-floor':
    get:
      tags:
        - shop floor
        - not implemented
        - no tests
      description: get basic shop floor info
      responses:
        '200':
          description: Shop Floor object
          schema:
            $ref: '#/definitions/ShopFloor'
  '/resources/shop-floor/{bayId}':
    get:
      tags:
        - shop floor
        - not implemented
        - no tests
      description: Get information on specific bay
      parameters:
        - in: path
          name: bayId
          description: Bay Id
          type: integer
          required: true
      responses:
        200:
          description: returns Bay information details
          schema:
            $ref: '#/definitions/Bay'
  '/resources/shop-floor/{bayId}/{machineId}':
    get:
      tags:
        - shop floor
        - not implemented
        - no tests
      description: Get information on specific machine in bay
      parameters:
        - name: bayId
          in: path
          type: integer
          description: bay Id
          required: true
        - name: machineId
          in: path
          type: integer
          description: Machine Id
          required: true
      responses:
        200:
          description: returns information on specified machine
          schema:
            $ref: '#/definitions/Machine'
  '/resources/workforce':
    get:
      tags:
        - workforce
        - not implemented
        - no tests
      description: Get workforce description
      responses:
        '200':
          description: Sends workforce information
          schema:
            $ref: '#/definitions/Workforce'
  '/resources/workforce/training/{trainingId}':
    get:
      tags:
        - workforce
        - not implemented
        - no tests
      description: Get Training method information
      parameters:
        - name: trainingId
          in: path
          type: integer
          description: training ID
          required: true
      responses:
        200:
          description: Sends workforce training information
          schema:
            $ref: '#/definitions/Training'
  '/resources/workforce/programs/{programId}':
    get:
      tags:
        - workforce
        - not implemented
        - no tests
      description: Get Program information
      parameters:
        - name: programId
          in: path
          type: integer
          description: programId
          required: true
      responses:
        200:
          description: Sends workforce programs information
          schema:
            $ref: '#/definitions/Program'
  '/resources/workforce/development/{developmentId}':
    get:
      tags:
        - workforce
        - not implemented
        - no tests
      description: Get Development information
      parameters:
        - name: developmentId
          in: path
          type: integer
          description: developmentId
          required: true
      responses:
        200:
          description: Sends workforce development information
          schema:
            $ref: '#/definitions/Development'
  '/resources/fellowship':
    get:
      tags:
        - fellowship
        - not implemented
        - no tests
      description: Get Fellowship info
      responses:
        '200':
          description: Sends Fellowship information
          schema:
            $ref: '#/definitions/Fellowship'
  '/resources/fellowship/{fellowId}':
    get:
      tags:
        - fellowship
        - not implemented
        - no tests
      description: Get Specified Fellow info
      parameters:
        - name: fellowId
          in: path
          type: integer
          description: fellowId
          required: true
      responses:
        200:
          description: Sends Fellow information
          schema:
            $ref: '#/definitions/Fellow'
  '/resources/projects':
    get:
      tags:
        - projects
        - not implemented
        - no tests
      description: Get Project info
      responses:
        200:
          description: Sends Project information
          schema:
            $ref: '#/definitions/Projects'
  '/resources/projects/currentProjects/{projectId}':
    get:
      tags:
        - projects
        - not implemented
        - no tests
      description: Get current Project info
      parameters:
        - name: projectId
          in: path
          type: integer
          description: projectId
          required: true
      responses:
        200:
          description: Sends current Project information
          schema:
            $ref: '#/definitions/Project'
  '/resources/projects/upcomingProjects/{projectId}':
    get:
      tags:
        - projects
        - not implemented
        - no tests
      description: Get upcoming Project info
      parameters:
        - name: projectId
          in: path
          type: integer
          description: projectId
          required: true
      responses:
        200:
          description: Sends upcoming Project information
          schema:
            $ref: '#/definitions/Project'
  '/resources/miscellaneous':
    get:
      tags:
        - miscellaneous
        - not implemented
        - no tests
      description: Get miscellaneous info
      responses:
        '200':
          description: Sends miscellaneous information
          schema:
            $ref: '#/definitions/Miscellaneous'
definitions:
  FeatureImage:
    type: object
    properties:
      thumbnail:
        type: string
      large:
        type: string
  UILabs:
    type: object
    properties:
      logo:
        type: string
      description:
        type: string
      process:
        type: string
      featureImage:
        $ref: '#/definitions/FeatureImage'
      labs:
        type: array
        items:
          $ref: '#/definitions/Lab'
  Lab:
    type: object
    properties:
      labId:
        type: integer
      name:
        type: string
      logo:
        type: string
      desciption:
        type: string
      link:
        type: string
  ShopFloor:
    type: object
    properties:
      shopImage:
        type: string
      about:
        type: string
      shopBays:
        type: array
        items:
          $ref: '#/definitions/Bay'
  Bay:
    type: object
    properties:
      bayId:
        type: integer
      bayName:
        type: string
      bayDescription:
        type: string
      bayImage:
        $ref: '#/definitions/FeatureImage'
      bayMachines:
        type: array
        items:
          $ref: '#/definitions/Machine'
  Machine:
    type: object
    properties:
      machineId:
        type: integer
      machineName:
        type: string
      machineDescription:
        type: string
      machineImage:
        $ref: '#/definitions/FeatureImage'
  Workforce:
    type: object
    properties:
      about:
        type: string
      workforceImage:
        $ref: '#/definitions/FeatureImage'
      training:
        type: array
        items:
          $ref: '#/definitions/Training'
      programs:
        type: array
        items:
          $ref: '#/definitions/Program'
      development:
        type: array
        items:
          $ref: '#/definitions/Development'
  Training:
    type: object
    properties:
      trainingId:
        type: integer
      title:
        type: string
      trainingImage:
        $ref: '#/definitions/FeatureImage'
      description:
        type: string
  Program:
    type: object
    properties:
      programId:
        type: integer
      title:
        type: string
      programImage:
        $ref: '#/definitions/FeatureImage'
      description:
        type: string
  Development:
    type: object
    properties:
      developmentId:
        type: integer
      title:
        type: string
      developmentImage:
        $ref: '#/definitions/FeatureImage'
      description:
        type: string
  Fellowship:
    type: object
    properties:
      about:
        type: string
      image:
        type: string
      fellows:
        type: array
        items:
          $ref: '#/definitions/Fellow'
      becomeAFellow:
        type: string
      contact:
        type: string
  Fellow:
    type: object
    properties:
      fellowId:
        type: integer
      fellowImage:
        $ref: '#/definitions/FeatureImage'
      fellowInfo:
        type: string
  Projects:
    type: object
    properties:
      about:
        type: string
      currentProjects:
        type: array
        items:
          $ref: '#/definitions/Project'
      upcomingProjects:
        type: array
        items:
          $ref: '#/definitions/Project'
  Project:
    type: object
    properties:
      projectId:
        type: integer
      title:
        type: string
      description:
        type: string
      featureImage:
        $ref: '#/definitions/FeatureImage'
      images:
        type: string
      startDate:
        type: number
      endDate:
        type: number
      collaborators:
        type: array
        items:
          $ref: '#/definitions/Collaborator'
      current:
        type: boolean
  Collaborator:
    type: object
    properties:
      organizationId:
        type: integer
      title:
        type: string
      image:
        type: string
  Miscellaneous:
    type: object
    properties:
      description:
        type: string
      externalLinks:
        type: array
        items:
          $ref: '#/definitions/ExternalLinks'
  ExternalLinks:
    type: object
    properties:
      title:
        type: string
      link:
        type: string
